### PR TITLE
add upload APIs

### PR DESCRIPTION
**Pull request by entotsu**

### CODE REVIEW

**Comment by parroty** [comment]
Thanks. It's about https://dev.twitter.com/rest/reference/post/media/upload, correct?

Regarding the new api, is it possible to update `lib/extwitter.ex` which lists up the API interfaces?
Also, having an example in the `test/extwitter_test.exs` would be great (though I'm not confident if file-uploading works well in the current framework, yet).

**Comment by parroty** [comment]
@entotsu Is it possible for you to post an example usage for uploading file with this API? 

I'm trying the PR with the following code, but facing `media type unrecognized` error when calling `1.1/statuses/update.json` API.

```elixir
image = File.read!("sample_image.png")
ExTwitter.API.Tweets.upload_tweet("test_upload", image)
```

I'm looking for a way to isolate the issue.  
One concern is the document says to use `multipart/form-data`, but I think current call is using simple post request.

**Comment by entotsu** [comment]
Thanks!

This is my code.

``` elixir
status = "hello!"
{:ok, res} = HTTPoison.get(url)
image = Base.encode64(res.body)// optional
ExTwitter.API.Tweets.upload_tweet(status, image)
```

This code is working in my project.
https://github.com/entotsu/Dribbble-GIF-bot

**Comment by parroty** [comment]
Thanks, it worked.
(I was not using Base64 encoding previously as `media` parameter instead of `media_data` was used).  
Please allow a little more time for the merge (I would like to experiment a little more).

I'm thinking to add `ExTwitter.update_with_media(status, data, options \\ [])` by also including `Base.encode64` part.
(https://dev.twitter.com/rest/reference/post/statuses/update_with_media
seems deprecated but name itself makes sense.)

**Comment by entotsu** [comment]
Thanks!! :grin: 
I am really glad!!

**Comment by entotsu** [comment]
GJ!! :+1:

**Comment by parroty** [comment]
Thanks! 
I could confirm relatively large (around 1MB) image upload. But, it seems video files requires chunked upload, so noted in API doc at the moment (server returns "media type unrecognized" error).

https://twittercommunity.com/t/uploading-video-in-node-js-always-400-media-type-unrecognized/45825/4

**Pull request merged**
