### PR TITLE
Added media chunk upload functionality

### PR DESCRIPTION
**Pull request by raymondboswel**
I wrote the code in this pull request to support sending videos, images and gifs using the new beta DM api. I'm leaving out my updated DM code (which supports media and quick replies) as I couldn't get the OAuth working using httpc and added in HTTPoison instead. Let me know if you're interested in the code and I'll create a separate pull request.

### CODE REVIEW

**Comment by raymondboswel** [comment]
The build fails for elixir 1.2 as default parameter values aren't supported in delegated functions. If support is required I can make the chunk size a required parameter. It currently defaults to 65k.

**Comment by parroty** [comment]
Thanks for the PR!

> The build fails for elixir 1.2 as default parameter values aren't supported in delegated functions. If support is required I can make the chunk size a required parameter. It currently defaults to 65k.

Can you try adding the `upload_media/2` for applying default parameter? I think some of the existing apis are defining similarly (though maybe it would be good to apply defdelegate with default parameter at some point).

`defdelegate upload_media(path, content_type), to: ExTwitter.API.Base`

Also, it would be great if you could note that default chunk size is 65k, in the `@doc` for the corresponding api endpoint (in `extwitter.ex`).

**Comment by raymondboswel** [comment]
Sounds good! I'll update the PR tomorrow :+1:

**Comment by raymondboswel** [comment]
I've updated the PR to include the suggestions. I'll see if I can get around to adding tests at some point, but I'll have to get back to my real work now :)

**Comment by parroty** [comment]
Thanks!

**Pull request merged**
