### PR TITLE
Misc doc changes

### PR DESCRIPTION
**Pull request by kianmeng**
Besides other documentation changes, this commit ensures the generated
HTML doc for HexDocs.pm will become the source of truth for this Elixir
library and leverage on latest features of ExDoc.

### CODE REVIEW

**Comment by kianmeng** [comment]
@parroty Should I resolve the conflict and resubmit the PR again?

**Comment by parroty** [comment]
Thanks for the extensive change, and I'm sorry for not responding when it was submitted. Yes, I appreciate if you could resolve the conflict.

**Comment by kianmeng** [comment]
@parroty Done. Please check again.

**Comment by parroty** [comment]
Thanks for the extensive updates!

**Comment by kianmeng** [comment]
:+1: :tada:

**Pull request merged**
