### PR TITLE
Allow for multiple tweets in a given message 

### PR DESCRIPTION
**Pull request by pjskennedy**
I noticed internal Poison parsing errors while using the streaming API:

```
[error] Error returned, stopping stream ({{:invalid, "{", 8142}, "{\"created_at\":\"Sat Oct 13 23:00:18 +0000 2018\"...
```

Twitter's [API Doc's](https://developer.twitter.com/en/docs/tutorials/consuming-streaming-data.html):
> note that Tweets and other streamed messages will not necessarily fall on HTTP chunk boundaries – be sure to use the delimiter defined above to determine activity boundaries when reassembling the stream.

I took a look into the code and found that sometimes detecting an "end of tweet" was not detecting there was actually two (or more) tweet JSON documents concatenated together. It looks as though each HTTP Chunk returned could have multiple tweets in it.

The line feed (`\r\n`) is always to delimit tweets in this API, even if it exists in a following chunk. The existing code was skipping "Empty" messages (messages that are only line feeds), however these line feeds are often marking the end of a tweet in a previous chunk in the HTTP response. This is what was leading to appended JSON documents and corresponding JSON parse failures.

### CODE REVIEW

**Comment by jessiahr** [comment]
Is there a plan to merge this? `stream_filter` errors out as soon as it hits an :invalid response, would be nice to not have to restart it.

**Comment by KristerV** [comment]
i guess i'll use the fork then

**Comment by KristerV** [comment]
I've cherry-picked this commit on top of `extwitter` 0.12.4. Not going to guarantee being up to date, but for now it's a solution. https://github.com/KristerV/extwitter

**Comment by parroty** [comment]
I'm sorry about not responding this item. It might be too late, but if you have working change on top of the latest one, is it possible for you to open PR?

**Comment by KristerV** [comment]
Ideally you would rebase this one, at least GitLab has that option right in this UI.

Anyway - if the button isn't here I made the PR: #148
As far as I can tell I did preserve @pjskennedy's name in the commit

**Comment by pjskennedy** [comment]
Hi @parroty and @KristerV 

I have rebased, this should be good to merge now.

**Comment by parroty** [comment]
Thank you for the updates, and I'm sorry about taking so long to merge.

**Comment by KristerV** [comment]
hey no worries and thanks for the package!

**Pull request merged**
