### PR TITLE
Minor adjustments while running on Elixir v1.1.1

### PR DESCRIPTION
**Pull request by omnibs**
I've run into problems while trying to run the package today on v1.1.1.

I've added `>=` to Elixir version in `mix.exs`. Since mix doesn't download Elixir, we were just preventing pre-release users from using the package. v1.1.1 shouldn't be pre-release today, but somehow mix was complaining.

```
** (Mix) You're trying to run :extwitter on Elixir v1.1.1 but it has 
declared in its mix.exs file it supports only Elixir ~> 1.0.0
```

Aside from that, exvcr seem to have added meck to dev dependencies and mix was complaining about that as well.

```
Unchecked dependencies for environment test:
* meck (Hex package)
  the dependency meck

  > In mix.exs:
    {:meck, "~> 0.8.2", [hex: :meck, only: :test]}

  does not match the environments calculated for

  > In deps/exvcr/mix.exs:
    {:meck, "~> 0.8.2", [only: [:dev, :test], optional: false, hex: :meck]}

  Ensure the parent dependency specifies a superset of the child one in your dep
** (Mix) Can't continue due to errors on dependencies
```

### CODE REVIEW

**Comment by omnibs** [comment]
I bumped Elixir to v1.1.1 on travis also, and the enviroment's blowing up because of that. Weird error, will google that later.

**Comment by omnibs** [comment]
[This](https://github.com/elixir-lang/elixir/issues/3458) indicated bumping Erlang to 18 could help. It did.

What that indicates, it seems, is that Elixir v1.1.1 on Travis is compiled against Erlang 18. I'll research some more or ask around how to get around that.

**Comment by omnibs** [comment]
Got some info on `#elixir-lang`

```
[13:13:27] <omnibs> I get this error on v1.1.1 + opt 17.1 on travis ci: https://github.com/elixir-lang/elixir/issues/3458
[13:13:46] <omnibs> v1.1.1 supports 17.1 right?
[13:15:21] <micmus> omnibs: Are you using the precompiled elixir?
[13:15:40] <omnibs> micmus: IDK where travis gets it's elixir :{
[13:16:39] <omnibs> hm
[13:16:48] <omnibs> it gets elixir from hex
[13:16:57] <micmus> omnibs: I think earlier today ericmj pointed out it's because the precompiled elixir is build on 18
[13:17:02] <micmus> That's the precompiled one
[13:17:11] <micmus> Erlang 18
[13:18:20] <ericmj> That's correct, I haven't had time to fix it yet
```

**Comment by parroty** [comment]
Thanks for the PR! 
If the error is about precompile on the elixir itself, I think I can merge (is it ready to merge?)
Maybe testing target can be 17.4 and 18.1.

**Comment by omnibs** [comment]
Okay, I'll change the target to 17.4 and 18.1!
Sorry for the delay, was coming back from ElixirConf! =]

**Comment by omnibs** [comment]
oops, didn't see you had already merged

**Comment by parroty** [comment]
Thanks! Your comment helped on updating .travis.yml.

**Pull request merged**
